server:
  port: 6003
  compression: 
    enabled: true
  tomcat: 
    uri-encoding: UTF-8
    
spring:
  application:
    name: cloud-paas-portal
  cloud: 
    consul: 
      host: localhost
      port: 8500 
      discovery:
        ip-address: localhost
        prefer-ip-address: true
        tags: huangyan
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_paas_portal?useUnicode=true&characterEncoding=utf8
    username: appuser
    password: 123456
  redis:
    host: localhost
    port: 6379
  cache:
    ehcache:
      config: classpath:ehcacheConfig.xml

mybatis:
  type-aliases-package: com.cloud.paas.portal.domain
  mapper-locations: classpath*:persistence-mapper/**/*Mapper.xml
  config-location: classpath:mybatisConfig.xml  
  
hystrix: 
  threadpool: 
    default: 
      coreSize: 500
  command: 
    paas-file: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 3600000
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 8000  