server:
  port: 80

spring:
  application:
    name: cloud-paas-api-gateway
  mvc:
    favicon:
      enabled: false
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
          ip-address: localhost
          prefer-ip-address: true
          tags: api-gateway-huangyan
  redis:
    host: localhost
    port: 6379   

zuul: 
  sensitive-headers: "*"
  routes: 
    cloud-paas-portal: 
      path: /**
      strip-prefix: true
      service-id: cloud-paas-portal
hystrix: 
  threadpool: 
    default: 
      coreSize: 500  #并发执行的最大线程数，默认10
  command: 
    paas-file: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 3600000 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 8000  #命令执行超时时间，默认1000ms
            
            